#!/usr/bin/env bash

###########################
# Command Line
###########################

for i in "$@"
do
case $i in
    --help)
    SHOW_HELP=1
    shift
    ;;
    --push)
    PUSH=1
    shift
    ;;
    *)
       # unknown option
    ;;
esac
done

###########################
# Functions
###########################

show_help ()
{
  echo ""
  echo "Pulls the installspace from the server to /opt/yujin/indigo."
  echo "Make sure you call this with sudo or set the correct permissions"
  echo "on /opt/yujin."
  echo ""
  echo "    Usage:"
  echo "        sudo groot_binaries"
  echo ""
  echo "    Options:"
  echo "        --help      : this help message"
  echo ""
  echo "    Admin Options:"
  echo "        --push      : push local /opt/yujin/indigo installspace with the server"
  echo ""
  exit 0
}

if [ ! -z "$SHOW_HELP" ]; then
  show_help
  exit 0
fi

export remote_url=files@files.yujin.com
export local_dir=/opt/yujin  # this copies the indigo folder
export remote_dir=${remote_url}:shared/repos/installspaces/yujin

# Options
# --delete    : files from the destination directories
# --recursive : recurse into directories
# --links     : copy symlinks as symlinks

export OPTIONS="--delete --recursive --links --verbose"
#EXCLUDES=(
#  --exclude '*.pyc'
#)

if [ ! -z "$PUSH" ]; then
    echo ""
    echo "Do you really want to push changes (if you aren't sure, you definitely do not)?[y/N]:"
    read answer
    if [ "$answer" == "y" ]; then
        rsync ${OPTIONS} ${local_dir}/indigo ${remote_dir}
    else
        echo "Aborting."
    fi
    echo ""
else
    rsync ${OPTIONS} ${remote_dir}/indigo ${local_dir}
fi

