#!/bin/bash

PACKAGES_URI="packages.yujinrobot.com"
PACKAGES_URL="http://${PACKAGES_URI}"
PACKAGES_SSH="files@${PACKAGES_URI}"
PACKAGES_SCRIPTS_DIR="/data/repos/scripts"
UBUNTU_ARCH=amd64
UBUNTU_VERSION_string="trusty"
CPACK_PACKAGE_NAME="python-yujin-tools"
COMPONENT_NAME=""
DEBIAN_FILENAME=`ls python-yujin-tools*.deb`

ssh ${PACKAGES_SSH} "rm -f ~/${DEBIAN_FILENAME}"
echo " -- ssh ${PACKAGES_SSH} -t '/data/repos/scripts/rem_deb ${UBUNTU_VERSION_string} ${CPACK_PACKAGE_NAME}'"
ssh ${PACKAGES_SSH} -t "/data/repos/scripts/rem_deb ${UBUNTU_VERSION_string} ${CPACK_PACKAGE_NAME}"
#ssh ${PACKAGES_SSH} -t '/data/repos/scripts/rem_deb ${UBUNTU_VERSION_string} ${CPACK_PACKAGE_NAME}-${COMPONENT_NAME}'
echo " -- scp ${DEBIAN_FILENAME} ${PACKAGES_SSH}:"
scp ${DEBIAN_FILENAME} ${PACKAGES_SSH}:
echo " -- ssh ${PACKAGES_SSH} '/data/repos/scripts/add_deb ${UBUNTU_ARCH} ${UBUNTU_VERSION_string} ${DEBIAN_FILENAME}'"
ssh ${PACKAGES_SSH} -t "/data/repos/scripts/add_deb ${UBUNTU_ARCH} ${UBUNTU_VERSION_string} ${DEBIAN_FILENAME}"
echo " -- ssh ${PACKAGES_SSH} 'rm -f ~/${DEBIAN_FILENAME}'"
ssh ${PACKAGES_SSH} "rm -f ~/${DEBIAN_FILENAME}"

