#!/usr/bin/env python

import sys
import yujin_tools
import yujin_tools.console as console

if __name__ == '__main__':
    try:
        sys.exit(yujin_tools.init_build())
    except Exception as e:
        console.logerror(str(e))
        sys.exit(1)

