#!/usr/bin/env python

import sys
import yujin_tools
import termcolor

if __name__ == '__main__':
    try:
        sys.exit(yujin_tools.ansible.main())
    except Exception as e:
        termcolor.colored(str(e), 'red')
        sys.exit(1)
