#!/bin/bash

###########################
# Methods
###########################

show_help ()
{
  echo ""
  echo "Updates your yujin tools installation (requires sudo)."
  echo ""
  echo "    Usage:"
  echo "        yujin_tools_update"
  echo ""
  exit 0
}

###########################
# Program
###########################

if [ "$1" == "--help" ]; then
  show_help
  exit 0
fi

sudo pip install -U yujin_tools