#!/bin/bash
# This only needed by ubuntu karmic, otherwise comment out
export GDK_NATIVE_WINDOWS=1

export YUJIN_WORKSPACE=%(cwd)s
if [ -d ${YUJIN_WORKSPACE}/devel ]; then
  source ${YUJIN_WORKSPACE}/devel/setup.bash
  alias cddevel="cd ${YUJIN_WORKSPACE}/build/devel"
  alias m1="export ROS_MASTER_URI=http://localhost:11311"
  alias m2="export ROS_MASTER_URI=http://localhost:11312"
  alias m3="export ROS_MASTER_URI=http://localhost:11313"
  alias m4="export ROS_MASTER_URI=http://localhost:11314"
  alias m5="export ROS_MASTER_URI=http://localhost:11315"
fi
# Add the full path if eclipse is not in PATH
exec /opt/yujin/eclipse/eclipse -data ~/workspace/%(name)s
